sudo: required
services:
  - docker
script:
  - docker build -t cloud .
after_success:
  -docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  -docker tag laboratorio $DOCKER_USER/laboratorio
  -docker push $DOCKER_USER/laboratorio